version: "3.8"
services:
  profilasatidz:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./asatidz.json:/root/asatidz.json
      - ./asatidz_enriched.json:/root/asatidz_enriched.json
    restart: unless-stopped
